

def generate_prompt_templates(n_placeholders):

    if n_placeholders > 0:
        prompt_templates = [
            'a bad photo of a {} often including ' + ', '.join(['a {}'] * n_placeholders) + '.', 
            'a photo of many {} often including ' + ', '.join(['many {}'] * n_placeholders) + '.', 
            'a sculpture of a {} often coocurring with ' + ', '.join(['a {}'] * n_placeholders) + '.', 
            'a photo of the hard to see {} often including ' + ', '.join(['the hard to see {}'] * n_placeholders) + '.', 
            'a low resolution photo of the {} often including ' + ', '.join(['the {}'] * n_placeholders) + '.', 
            'a rendering of a {} often including ' + ', '.join(['a {}'] * n_placeholders) + '.', 
            'graffiti of a {} often including ' + ', '.join(['a {}'] * n_placeholders)  + '.', 
            'a bad photo of the {} often including ' + ', '.join(['the {}'] * n_placeholders) + '.', 
            'a cropped photo of the {} often including ' + ', '.join(['the {}'] * n_placeholders) + '.', 
            'a tattoo of a {} often including ' + ', '.join(['a {}'] * n_placeholders) + '.', 
            'the embroidered {} often coocurring with ' + ', '.join(['embroidered {}'] * n_placeholders) + '.', 
            'a photo of a hard to see {} often including ' + ', '.join(['a hard to see {}'] * n_placeholders) + '.', 
            'a bright photo of a {} often including ' + ', '.join(['a {}'] * n_placeholders) + '.', 
            'a photo of a clean {} often including ' + ', '.join(['a clean {}'] * n_placeholders) + '.', 
            'a photo of a dirty {} often including ' + ', '.join(['a dirty {}'] * n_placeholders)  + '.', 
            'a dark photo of the {} often including ' + ', '.join(['the {}'] * n_placeholders) + '.', 
            'a drawing of a {} often including ' + ', '.join(['a {}'] * n_placeholders) + '.', 
            'a photo of my {} often including ' + ', '.join(['my {}'] * n_placeholders) + '.',
            'the plastic {} often coocurring with ' + ', '.join(['the plastic {}'] * n_placeholders) + '.', 
            'a photo of the cool {} often including ' + ', '.join(['the cool {}'] * n_placeholders) + '.', 
            'a close-up photo of a {} often including ' + ', '.join(['a {}'] * n_placeholders) + '.', 
            'a black and white photo of the {} often including ' + ', '.join(['the {}'] * n_placeholders) + '.', 
            'a painting of the {} often including ' + ', '.join(['the {}'] * n_placeholders) + '.', 
            'a painting of a {} often including ' + ', '.join(['a {}'] * n_placeholders) + '.', 
            'a pixelated photo of the {} often including ' + ', '.join(['the {}'] * n_placeholders) + '.', 
            'a sculpture of the {} often coocurring with ' + ', '.join(['the {}'] * n_placeholders) + '.', 
            'a bright photo of the {} often including ' + ', '.join(['the {}'] * n_placeholders) + '.', 
            'a cropped photo of a {} often including ' + ', '.join(['a {}'] * n_placeholders) + '.', 
            'a plastic {} often coocurring with ' + ', '.join(['a plastic {}'] * n_placeholders) + '.', 
            'a photo of the dirty {} often including ' + ', '.join(['the dirty {}'] * n_placeholders) + '.', 
            'a jpeg corrupted photo of a {} often including ' + ', '.join(['a {}'] * n_placeholders) + '.', 
            'a blurry photo of the {} often including ' + ', '.join(['the {}'] * n_placeholders) + '.', 
            'a photo of the {} often including ' + ', '.join(['the {}'] * n_placeholders) + '.', 
            'a good photo of the {} often including ' + ', '.join(['the {}'] * n_placeholders) + '.', 
            'a rendering of the {} often including ' + ', '.join(['the {}'] * n_placeholders) + '.', 
            'a {} in a video game often coocurring with ' + ', '.join(['a {}'] * n_placeholders) + '.', 
            'a photo of one {} often including ' + ', '.join(['one {}'] * n_placeholders) + '.', 
            'a doodle of a {} often including ' + ', '.join(['a {}'] * n_placeholders) + '.', 
            'a close-up photo of the {} often including ' + ', '.join(['the {}'] * n_placeholders) + '.', 
            'a photo of a {} often including ' + ', '.join(['a {}'] * n_placeholders) + '.',
            'the origami {} often coocurring with ' + ', '.join(['the origami {}'] * n_placeholders) + '.', 
            'the {} in a video game often coocurring with ' + ', '.join(['the {}'] * n_placeholders) + '.', 
            'a sketch of a {} often including ' + ', '.join(['a {}'] * n_placeholders) + '.', 
            'a doodle of the {} often including ' + ', '.join(['the {}'] * n_placeholders) + '.', 
            'a origami {} often coocurring with ' + ', '.join(['a origami {}'] * n_placeholders) + '.', 
            'a low resolution photo of a {} often including ' + ', '.join(['a {}'] * n_placeholders) + '.', 
            'the toy {} often coocurring with ' + ', '.join(['the toy {}'] * n_placeholders) + '.', 
            'a rendition of the {} often including ' + ', '.join(['the {}'] * n_placeholders) + '.',
            'a photo of the clean {} often including ' + ', '.join(['the clean {}'] * n_placeholders) + '.', 
            'a photo of a large {} often including ' + ', '.join(['a large {}'] * n_placeholders) + '.', 
            'a rendition of a {} often including ' + ', '.join(['a {}'] * n_placeholders) + '.', 
            'a photo of a nice {} often including ' + ', '.join(['a nice {}'] * n_placeholders) + '.', 
            'a photo of a weird {} often including ' + ', '.join(['a weird {}'] * n_placeholders) + '.', 
            'a blurry photo of a {} often inlcuding ' + ', '.join(['a {}'] * n_placeholders) + '.', 
            'a cartoon {} often coocurring with ' + ', '.join(['a cartoon {}'] * n_placeholders) + '.', 
            'art of a {} often including ' + ', '.join(['a {}'] * n_placeholders) + '.', 
            'a sketch of the {} often including ' + ', '.join(['the {}'] * n_placeholders) + '.', 
            'a embroidered {} often coocurring with ' + ', '.join(['a {}'] * n_placeholders) + '.', 
            'a pixelated photo of a {} often including ' + ', '.join(['a {}'] * n_placeholders) + '.', 
            'itap of the {} often including ' + ', '.join(['the {}'] * n_placeholders) + '.', 
            'a jpeg corrupted photo of the {} often including ' + ', '.join(['the {}'] * n_placeholders) + '.', 
            'a good photo of a {} often including ' + ', '.join(['a {}'] * n_placeholders) + '.', 
            'a plushie {} often coocurring with ' + ', '.join(['a plushie {}'] * n_placeholders) + '.', 
            'a photo of the nice {} often including ' + ', '.join(['the nice {}'] * n_placeholders) + '.', 
            'a photo of the small {} often including ' + ', '.join(['the small {}'] * n_placeholders) + '.', 
            'a photo of the weird {} often including ' + ', '.join(['the weird {}'] * n_placeholders) + '.', 
            'the cartoon {} often coocurring with ' + ', '.join(['the cartoon {}'] * n_placeholders) + '.', 
            'art of the {} often including ' + ', '.join(['the {}'] * n_placeholders) + '.', 
            'a drawing of the {} often including ' + ', '.join(['the {}'] * n_placeholders) + '.', 
            'a photo of the large {} often including ' + ', '.join(['the large {}'] * n_placeholders) + '.', 
            'a black and white photo of a {} often including ' + ', '.join(['a {}'] * n_placeholders) + '.', 
            'the plushie {} often coocurring with ' + ', '.join(['the plushie {}'] * n_placeholders) + '.', 
            'a dark photo of a {} often including ' + ', '.join(['a {}'] * n_placeholders) + '.', 
            'itap of a {} often including ' + ', '.join(['a {}'] * n_placeholders) + '.', 
            'graffiti of the {} often including ' + ', '.join(['the {}'] * n_placeholders) + '.', 
            'a toy {} often coocurring with ' + ', '.join(['a toy {}'] * n_placeholders) + '.', 
            'itap of my {} often including ' + ', '.join(['my {}'] * n_placeholders) + '.', 
            'a photo of a cool {} often including ' + ', '.join(['a cool {}'] * n_placeholders) + '.', 
            'a photo of a small {} often including ' + ', '.join(['a small {}'] * n_placeholders), 
            'a tattoo of the {} often including ' + ', '.join(['the {}'] * n_placeholders) + '.', 
            'there is a {} in the scene often including ' + ', '.join(['a {}'] * n_placeholders) + '.', 
            'there is the {} in the scene often including ' + ', '.join(['the {}'] * n_placeholders) + '.', 
            'this is a {} in the scene often inlcuding ' + ', '.join(['a {}'] * n_placeholders) + '.', 
            'this is the {} in the scene often including ' + ', '.join(['the {}'] * n_placeholders) + '.', 
            'this is one {} in the scene often including ' + ', '.join(['one {}'] * n_placeholders) + '.'
            ]
    else:
        prompt_templates = ['a bad photo of a {}.', 'a photo of many {}.', 'a sculpture of a {}.', 'a photo of the hard to see {}.', 'a low resolution photo of the {}.', 'a rendering of a {}.', 'graffiti of a {}.', 'a bad photo of the {}.', 'a cropped photo of the {}.', 'a tattoo of a {}.', 'the embroidered {}.', 'a photo of a hard to see {}.', 'a bright photo of a {}.', 'a photo of a clean {}.', 'a photo of a dirty {}.', 'a dark photo of the {}.', 'a drawing of a {}.', 'a photo of my {}.', 'the plastic {}.', 'a photo of the cool {}.', 'a close-up photo of a {}.', 'a black and white photo of the {}.', 'a painting of the {}.', 'a painting of a {}.', 'a pixelated photo of the {}.', 'a sculpture of the {}.', 'a bright photo of the {}.', 'a cropped photo of a {}.', 'a plastic {}.', 'a photo of the dirty {}.', 'a jpeg corrupted photo of a {}.', 'a blurry photo of the {}.', 'a photo of the {}.', 'a good photo of the {}.', 'a rendering of the {}.', 'a {} in a video game.', 'a photo of one {}.', 'a doodle of a {}.', 'a close-up photo of the {}.', 'a photo of a {}.', 'the origami {}.', 'the {} in a video game.', 'a sketch of a {}.', 'a doodle of the {}.', 'a origami {}.', 'a low resolution photo of a {}.', 'the toy {}.', 'a rendition of the {}.', 'a photo of the clean {}.', 'a photo of a large {}.', 'a rendition of a {}.', 'a photo of a nice {}.', 'a photo of a weird {}.', 'a blurry photo of a {}.', 'a cartoon {}.', 'art of a {}.', 'a sketch of the {}.', 'a embroidered {}.', 'a pixelated photo of a {}.', 'itap of the {}.', 'a jpeg corrupted photo of the {}.', 'a good photo of a {}.', 'a plushie {}.', 'a photo of the nice {}.', 'a photo of the small {}.', 'a photo of the weird {}.', 'the cartoon {}.', 'art of the {}.', 'a drawing of the {}.', 'a photo of the large {}.', 'a black and white photo of a {}.', 'the plushie {}.', 'a dark photo of a {}.', 'itap of a {}.', 'graffiti of the {}.', 'a toy {}.', 'itap of my {}.', 'a photo of a cool {}.', 'a photo of a small {}.', 'a tattoo of the {}.', 'there is a {} in the scene.', 'there is the {} in the scene.', 'this is a {} in the scene.', 'this is the {} in the scene.', 'this is one {} in the scene.']
    
    return prompt_templates

if __name__ == '__main__':
        prompt = generate_prompt_templates(3)
        for p in prompt:
            print(p)